pipeline {
  environment {
    imagename = "ertadan/course_work"
    registryCredential = 'dockerhub_id'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git([url: 'https://github.com/ertadan/course_work.git', 
    branch:'main'])

      }
    }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build imagename
        }
      }
    }
    stage('Push Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push("$BUILD_NUMBER")
             dockerImage.push('latest')

          }
        }
      }
    }
    stage('Deploy') {
      steps{
        // If we plan to host it locally in docker
	 sh "docker run --rm -d -p80:80 ertadan/course_work:latest"
	
	//for deploying with Ansible in cluster
	//sh "ansible-playbook -i hosts ubuntu-playbook.yml --ask-become-pass"
      }
    }
  }
}